model_list:
  - model_name: xai/*
    litellm_params:
      model: xai/*
      api_key: os.environ/XAI_API_KEY
  - model_name: nvidia/*
    litellm_params:
      model: openai/*
      api_base: https://integrate.api.nvidia.com/v1
      api_key: os.environ/NVIDIA_API_KEY
  - model_name: groq/*
    litellm_params:
      model: groq/*
      api_key: os.environ/GROQ_API_KEY
  - model_name: openrouter/*
    litellm_params:
      model: openrouter/*
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: cerebras/*
    litellm_params:
      model: cerebras/*
      api_key: os.environ/CEREBRAS_API_KEY

general_settings:
  master_key: sk-litellm-key
  drop_params: true