/**
 * prisma-types.ts — Shim for Prisma-generated model types
 * 
 * These types were previously generated by `prisma generate`.
 * Now they are `any` stubs to allow the codebase to compile during 
 * the progressive migration to JSON-file reads.
 * 
 * Replace each `any` with a real TypeScript interface as each service is migrated.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

export type Role = any;
export type RoleTool = any;
export type RoleVariant = any;
export type RoleCategory = any;
export type Tool = any;
export type Skill = any;
export type Model = any;
export type ModelCapabilities = any;
export type ModelUsage = any;
export type ProviderConfig = any;
export type AgentConfig = any;
export type Project = any;
export type Workspace = any;
export type Card = any;
export type WorkOrderCard = any;
export type Bookmark = any;
export type FileIndex = any;
export type UsageLog = any;
export type AgentRun = any;
export type AgentStep = any;
export type McpServer = any;
export type McpTool = any;
export type VectorChunk = any;
export type VectorEmbedding = any;
export type Orchestration = any;
export type Job = any;
